routes/web.php
<?php
Route::get('/', function(){
	return view('kakakAsuh.frontPage.homekka');
});

// Error page
Route::get('/404',function(){
	return view('404');
})->name('404');
Route::get('/405',function(){
	return view('404');
})->name('405');

Auth::routes();
/* Activate Email*/
Route::get('auth/activate','Auth\ActivationController@activate')->name('auth.activate');
/*Resend Activate Email*/
Route::get('auth/activate/resend','Auth\ActivationResendController@showResendForm')->name('auth.activate.resend');
Route::post('auth/activate/resend','Auth\ActivationResendController@resend');

/*===== Form Register Start =====*/
Route::resource('kkaregis', 'Kka\RegisterController');
/*===== Form Register Start =====*/


Route::group(['middleware'=>['auth','role:student']], function(){  

	/*===== Dasboard Start =====*/
	Route::get('/home', 'PondokitController@index')->name('dashboard.home');
	// Route::get('/home', 'PondokitController@index')->name('dashboard.home');
	/*List santri*/
	Route::get('list/programmer','PondokitController@santriProgrammer')->name('list.programmer');
	Route::get('list/multimedia','PondokitController@santriMultimedia')->name('list.multimedia');
	Route::get('list/imers','PondokitController@santriImers')->name('list.imers');
	Route::get('list/cyber','PondokitController@santriCyber')->name('list.cyber');
	/*===== Dasboard End =====*/

	/*===== Activity Start =====*/
	Route::resource('activity', 'ActivityController');
	Route::get('api/activity','ActivityController@apiActivity')->name('api.activity');
	/*===== Activity End =====*/

	/*===== Goal Start =====*/
	Route::resource('goal', 'GoalController');
	Route::get('api/goal','GoalController@apiGoal')->name('api.goal');
	/*===== Goal End =====*/

	/*===== Profile Start ===== */
	Route::get('profile','ProfileController@index')->name('profile');
	// SHOW
	Route::get('profile/{id}','ProfileController@show')->name('profile.show');
	/*Edit*/
	Route::get('profile/{id}/edit','ProfileController@edit')->name('profile.edit');
	Route::patch('profile/{id}/edit','ProfileController@update')->name('profile.update');
	Route::get('profilepass/{id}/edit','ProfileController@passwordEdit')->name('profilepass.edit');
	Route::patch('profilepass/{id}/edit','ProfileController@passwordUpdate')->name('profilepass.update');

	/*===== Profile End ===== */

	/*===== 100 Dream Start ===== */
	Route::get('/100dream','ProfileController@dreamIndex')->name('dream');
	/*Edit*/
	Route::get('dream/{id}/edit','ProfileController@dreamEdit')->name('dream.edit');
	Route::patch('dream/{id}/edit','ProfileController@dreamUpdate')->name('dream.update');
	/*===== 100 Dream End ===== */

	/*===== Target Terdekat Start ===== */
	Route::get('/target','ProfileController@targetIndex')->name('target');
	/*Edit*/
	Route::get('target/{id}/edit','ProfileController@targetEdit')->name('target.edit');
	Route::patch('target/{id}/edit','ProfileController@targetUpdate')->name('target.update');
	/*===== Target Terdekat End ===== */

	/*===== Amaliyah Start ===== */
	Route::get('amaliyahcheck', 'AmaliyahController@checkAmaliyah')->name('amaliyahcheck');
	Route::get('amaliyah', 'AmaliyahController@index')->name('amaliyah.index');
	// create
	Route::get('amaliyah/create', 'AmaliyahController@create')->name('amaliyah.create');
	Route::post('amaliyah/create', 'AmaliyahController@store')->name('amaliyah.store');
	// edit
	// Route::get('amaliyah/edit', 'AmaliyahController@update')->name('amaliyah.edit');
	Route::patch('amaliyah/edit/{id}', 'AmaliyahController@update')->name('amaliyah.update');
	/*===== Amaliyah End ===== */

	/*===== Motor start =====*/
	Route::resource('motor','MotorController');
	Route::get('api/motor','MotorController@apiMotor')->name('api.motor');
	Route::get('done/motor/{id}','MotorController@done')->name('done.motor');
	/*===== Motor End =====*/

	/*====== Report to Foster Brother Start =========*/
	Route::resource('reporttoka','Kka\dashboard\ReportToKAController');
	Route::get('reporttoka/adikasuh/{id}','Kka\dashboard\ReportToKAController@allReportAdikAsuh')->name('reporttoka.adikasuh');
	/*====== Report to Foster Brother Start =========*/ 


	/*===== Kirim Saran Start=====*/
	Route::resources([
		'suggestion' => 'SuggestionController'
	]);
	/*===== Kirim Saran End=====*/
	
	/*=============================================================================================*/
	/*======================================== Caregiver Start ========================================*/
	/*=============================================================================================*/
	
	Route::get('kkasantri','Kka\dashboard\SantriController@index')->name('kka.santri');
	Route::get('charity','Kka\dashboard\SantriController@charity')->name('charity');

	Route::group(['middleware'=>['auth','role:foster_brother']], function(){
		Route::resource('caregiver','Kka\dashboard\CaregiverController');
		Route::resource('invoice','Kka\dashboard\invoice\InvoiceController');
		Route::get('api/invoice','Kka\dashboard\invoice\InvoiceController@apiInvoice')->name('api.invoice');
		Route::get('paket-amal/add/{id_santri}','Kka\dashboard\order\OrderController@create')->name('paket-amal.create');
		Route::post('paket-amal/add/{id_santri}','Kka\dashboard\order\OrderController@store')->name('paket-amal.store');
		/*Confirmation*/
		Route::get('konfirmasi','Kka\dashboard\invoice\ConfirmationController@create')->name('confirmation.create');
		Route::post('konfirmasi','Kka\dashboard\invoice\ConfirmationController@store')->name('confirmation.store');

		/** ===== Download Invoice ===== */
		Route::get('dowloadinvoice/{id}','Kka\dashboard\invoice\InvoiceController@downloadInvoice')->name('download.invoice');

		
		/*
		====== Adik Asuh Start =========
		*/ 
		// activity
		Route::get('activity/adik-asuh/{id}','Kka\dashboard\CaregiverController@indexActivtySantri')->name('adik.activity');
		//Api Activity apiActivtySantri
		Route::get('api-activity/adik-asuh/{id}','Kka\dashboard\CaregiverController@apiActivtySantri')->name('adik.api-activity');		
		//Taeget / Goal apiGoalSantri
		Route::get('target/adik-asuh/{id}','Kka\dashboard\CaregiverController@indexGoalSantri')->name('adik.target');
		//Api Target / Goal
		Route::get('api-target/adik-asuh/{id}','Kka\dashboard\CaregiverController@apiGoalSantri')->name('adik.api-target');				
		Route::get('amaliyah/adik-asuh/{id}','Kka\dashboard\CaregiverController@amaliyahIndex')->name('adik.amaliyah');

		/*
		====== Adik Asuh End =========
		*/ 
	});
	/*=============================================================================================*/
	/*======================================== Caregiver end ========================================*/
	/*=============================================================================================*/

	/*=============================================================================================*/
	/*======================================== Admin Start ========================================*/
	/*=============================================================================================*/
	// Route::group(['middleware'=>['auth','role:teacher']], function(){ /*Auth untuk chek admin atau bukan*/
	Route::group(['middleware'=>['auth','role:teacher']], function(){ /*Auth untuk chek admin atau bukan*/
		

		/*All Divisi*/
		Route::get('user/programmer','AllUserController@index')->name('user.programmer');
		Route::get('user/multimedia','AllUserController@index')->name('user.multimedia');
		Route::get('user/imers','AllUserController@index')->name('user.imers');
		Route::get('user/cyber','AllUserController@index')->name('user.cyber');
		Route::get('user/kka','AllUserController@index')->name('user.kka');
		// Delete Kakak asuh
		Route::delete('user/kka/{id}/delete','AllUserController@kkaDestroy')->name('user.kka.destroy');
		Route::get('user/staff','AllUserController@index')->name('user.staff');

		/*===== Acitivity Santri CRUD For The Admin Access Start =====*/
		/*Index*/
		Route::get('santri/report/{id}','AllUserController@indexActivtySantri')->name('santri.report');
		/*Create*/
		Route::get('santri/createreport/{id}','AllUserController@createActivitySantri')->name('santri.createreport');
		/*Store*/
		Route::post('santri/createreport/{id}','AllUserController@storeActivitySantri')->name('santri.storereport');
		/*Update*/
		Route::get('santri/editreport/{id}/edit','AllUserController@editActivitySantri')->name('santri.editreport');
		Route::patch('santri/editreport/{id}','AllUserController@updateActivitySantri')->name('santri.updatereport');
		/*Api*/
		Route::get('santri/report/api/{id}','AllUserController@apiActivtySantri')->name('santri.apireport');
		/*===== Acitivity Santri CRUD For Admin Access End =====*/

		/*===== Goal Santri CRUD For The Admin Access Start =====*/
		/*Index*/
		Route::get('santri/goal/{id}','AllUserController@indexGoalSantri')->name('santri.goal');
		/*Create*/
		Route::get('santri/creategoal/{id}','AllUserController@createGoalSantri')->name('santri.creategoal');
		/*Store*/
		Route::post('santri/creategoal/{id}','AllUserController@storeGoalSantri')->name('santri.storegoal');
		/*Update*/
		Route::get('santri/editgoal/{id}/edit','AllUserController@editGoalSantri')->name('santri.editgoal');
		Route::patch('santri/editgoal/{id}','AllUserController@updateGoalSantri')->name('santri.updategoal');
		/*Api*/
		Route::get('santri/goal/api/{id}','AllUserController@apiGoalSantri')->name('santri.apigoal');
		/*===== Goal Santri CRUD For Admin Access End =====*/

		/*===== All Activity Goal Start=====*/ 
		Route::get('allgoalactivity/{id}', 'AllActivityGoalController@index')->name('allactivitygoal');
		Route::get('api/activitysantri/{id}','AllActivityGoalController@apiActivity')->name('api.activitysantri');
		Route::get('api/goalsantri/{id}','AllActivityGoalController@apiGoal')->name('api.goalsantri');
		/*===== All Activity Goal End=====*/
		
		/*===== Daily Activity  Start=====*/ 

app/Http/Controllers/Kka/dashboard/CaregiverController.php
<?php

namespace App\Http\Controllers\Kka\dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Caregiver;
use App\Models\User;
use Illuminate\Support\Facades\Auth; //untukmenggunakan Controller Auth
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class CaregiverController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $caregivers = DB::table('caregivers')->select('*')
        ->where([
            ['caregiver',Auth::user()->id],
            ['active',true],
        ])->get();

        $count = DB::table('caregivers')->select('*')
        ->where([
            ['caregiver',Auth::user()->id],
            ['active',true],
        ])->count();
        
        return view('kakakAsuh.dashboard.adikAsuh.adik-asuh',compact('caregivers','user','count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /*
    =================================================
    ================= Adik Asuh  Start===============
    =================================================
     */

    //=====  Activity Start =====

    public function indexActivtySantri($id)
    {
        $idNow = $id;

        $activities = DB::table('users')
            ->select('activities.*')
            ->rightJoin('activities', 'activities.user_id', '=', 'users.id' )
            ->where('users.id', "$id")
            ->latest()->paginate(20);


            // dd($users);
        $url   = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url_array = explode('/', $url);
        $urls = end($url_array);
        
        
        return view('kakakAsuh.dashboard.adikAsuh.allActivity', compact('activities','idNow','urls'));
    }

    /*API*/
    public function apiActivtySantri($id){

        $activities = DB::table('users')
            ->select('activities.*')
            ->rightJoin('activities', 'activities.user_id', '=', 'users.id' )
            ->where('users.id', "$id")
            ->orderBy('id','desc');

        return Datatables::of($activities)->addColumn('action', function($activities){
            return '<a onclick="editActivity('.$activities->id.')" class="btn btn-outline btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i>&nbsp;&nbsp;&nbsp;Edit</a> '.
                '<a onclick="deleteActivity('.$activities->id.')" class="btn btn-outline btn-danger btn-xs"><i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;&nbsp;Delete</a> ';
        })->make(true);
        
    }
    //=====  Activity End ==========

    //=====  Goal/Target Start =====
    /*Index*/
    public function indexGoalSantri($id)
    {
        $idNow = $id;
        $goals = DB::table('users')
            ->select('goals.*')
            ->rightJoin('goals', 'goals.user_id', '=', 'users.id' )
            ->where('users.id', "$id")
            ->latest()->paginate(20);

        $url   = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $url_array = explode('/', $url);
        $urls = end($url_array);

        return view('kakakAsuh.dashboard.adikAsuh.allTarget', compact('goals','users','idNow', 'urls'));
    }
    // Api
    public function apiGoalSantri($id){

        $goals = DB::table('users')
            ->select('goals.*')
            ->rightJoin('goals', 'goals.user_id', '=', 'users.id' )
            ->where('users.id', "$id")
            ->orderBy('id', 'desc');

        return Datatables::of($goals)->addColumn('action', function($goals){
            return '<a onclick="editGoal('.$goals->id.')" class="btn btn-outline btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i>&nbsp;&nbsp;&nbsp;Edit</a> '.
                '<a onclick="deleteGoal('.$goals->id.')" class="btn btn-outline btn-danger btn-xs"><i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;&nbsp;Delete</a> ';
        })->make(true);
        
    }
    //=====  Goal/Target End =====    
    
    //=====  Amaliyah Start =====        
    public function amaliyahIndex($id){

        $santri = DB::table('users')->select('name')
                ->where('id','=',$id)->get();

        $amal = DB::table('amaliyahs')
               ->where('user_id', '=', $id)
               ->whereMonth('date', date('m'))
               ->get();

        $calender  = 'CAL_GREGORIAN';
        $month     = date('m');
        $year      = date('Y');
        $total_day = date('t');//cal_days_in_month($calender, $month, $year);

        return view('dashboard.admin.santri.santriAmaliyah',compact('santri','amal', 'month',  'total_day'));

    }
    //=====  Amaliyah End =====            
     /*
    =================================================
    ================= Adik Asuh  End ================
    =================================================
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Kka/dashboard/SantriController.php
<?php

namespace App\Http\Controllers\Kka\dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class SantriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = DB::table('users')->select('*')->whereIn('department',[
             'Programmer',
             'Multimedia',
             'Imers',
             'Cyber',
         ])->latest()->paginate(20);

        return view('dashboard.dashboard.listSantri',compact('students'));
    }

    public function charity()
    {
        return view('kakakAsuh.dashboard.orderForm');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/kakakAsuh/dashboard/menukka.blade.php
<li>
    <a href="{{route('dashboard.home')}}"><i class="fa fa-dashboard fa-fw"></i> Dasbor</a>
</li>
<li>
    <a href="#"><i class="fa fa-users fa-fw"></i> Santri<span class="fa arrow"></span></a>
  
            <ul class="nav nav-third-level">
                <li>
                    <a href="{{route('kka.santri')}}">Semua Santri</a>
                </li>
                <li>
                    <a href="{{route('list.programmer')}}">Programmer</a>
                </li>
                <li>
                    <a href="{{route('list.multimedia')}}">Multimedia</a>
                </li>
                <li>
                    <a href="{{route('list.imers')}}">Imers</a>
                </li>
                <li>
                    <a href="{{route('list.cyber')}}">Cyber</a>
                </li>
            </ul>
    <!-- /.nav-second-level -->
</li>
<li>
    <a href="{{route('profile')}}"> <i class="fa fa-user fa-fw"></i>Profil Saya</a>
</li>
<li>
    <a href="{{route('caregiver.index')}}"> <i class="fa fa-users fa-fw"></i>Adik Asuh Saya</a>
</li>
<li>
    <a href="{{route('kka.santri')}}"> <i class="fa fa-plus-circle fa-fw"></i>Tambah Adik Asuh</a>
</li>
<li>
    <a href="{{route('suggestion.create')}}"> <i class="fa fa-envelope-o fa-fw"></i>Kirim Saran</a>
</li>
<li>
    <a href="{{route('invoice.index')}}"> <i class="fa fa-money fa-fw"></i>Invoice Ku</a>
</li>
<li>
    <a href=""> <i class="fa fa-edit fa-fw"></i>Laporan</a>
</li>
<li>
    <a href="{{route('confirmation.create')}}"> <i class="fa fa-money fa-fw"></i>Konfirmasi Donasi</a>
</li>
<li>
    <a href=""> <i class="fa fa-book fa-fw"></i>Buku Panduan</a>
</li>

resources/views/kakakAsuh/dashboard/orderForm.blade.php
@extends('dashboard.masterdashboard')
@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/kakakAsuh/kakakAsuh.css')}}">
@endsection
@section('content')
<div id="page-wrapper">
<br>
<br>
	<div class="row">
	    <div class="col-lg-offset-2 col-lg-8">
	      <div class="panel panel-info">
	        <div class="panel-heading">
	          <h3 class="panel-title">Pilih Paket Kakak Asuh</h3>
	        </div>
	        <div class="panel-body">
	              <div class="row ">

	                 <form action="{{route('paket-amal.store',$id_santri)}}" method="post" role="form" action="">
	                    {{csrf_field()}}
	                    {{ method_field('POST') }}
	                <div class=" col-lg-offset-2 col-8"> 
	                   <div class="funkyradio col-lg-8 col-lg-offset-1">
	                   	@if($package->package == 'A')
	                   		<div class="funkyradio-info">
					            <input checked value="180000" type="radio" name="package" id="package-b" />
					            <label for="package-b">Paket B Rp 180.000,- perbulan</label>
					        </div>
					    @elseif($package->package == 'B')
					    	<div class="funkyradio-info">
					            <input checked value="108000" type="radio" name="package" id="package-a" />
					            <label for="package-a">Paket A Rp 108.000,- perbulan</label>
					        </div>
					    @else
	                   		<div class="funkyradio-info">
					            <input checked value="288000" type="radio" name="package" id="package-c" />
					            <label for="package-c">Paket C Rp 288.000,- perbulan</label>
					        </div>
	                   		<div class="funkyradio-info">
					            <input value="180000" type="radio" name="package" id="package-b" />
					            <label for="package-b">Paket B Rp 180.000,- perbulan</label>
					        </div>
					        <div class="funkyradio-info">
					            <input value="108000" type="radio" name="package" id="package-a" />
					            <label for="package-a">Paket A Rp 108.000,- perbulan</label>
					        </div>
					    @endif
					        <br>
					        <div class="form-group">
						        <select name="amount_month" class="form-control">
									<option value="6" >6 bulan</option>
									<option value="3">3 bulan</option>
									<option value="1">1 bulan</option>
								</select>
							</div>
							<div>
								<button id="submit" name="submit"  class="btn btn-info">Kirim</button>
							</div>
						</div>
					</div>
	                 
	                </div>
	                </form>
	              </div>
	        </div>
	      </div>
	    </div>
	  </div>
</div>
@endsection